services:
  postgres:
    image: postgres:17.3-alpine3.21
    environment:
      POSTGRES_DB: 'AskMe'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - AskMe:/var/lib/postgresql/data
    ports:
      - '5432:5432' # Порт PostgreSQL по умолчанию - 5432, не 5555
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d AskMe']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
volumes:
  AskMe: # Название тома должно совпадать с тем, что указано в volumes сервиса
