# Generated by Django 5.2 on 2025-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tag_hh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='question',
        ),
        migrations.AddField(
            model_name='like',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
