# Generated by Django 5.2 on 2025-04-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_answer_author_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='desc',
            field=models.CharField(default='desc_placeholder', max_length=20000),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='title_placeholder', max_length=1000),
        ),
    ]
