# Generated by Django 5.2 on 2025-04-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_answerlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answer_likes', to='app.answer'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to='app.question'),
        ),
    ]
