# Generated by Django 5.2 on 2025-04-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_answerlike_answer_alter_questionlike_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like_count',
        ),
    ]
