# Generated by Django 5.2 on 2025-05-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_profile_email_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
