# Generated by Django 5.2 on 2025-05-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
